# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Student(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, student_name: int=None, first_name: str=None, last_name: str=None, grades: Dict[str, float]=None):  # noqa: E501
        """Student - a model defined in Swagger

        :param student_name: The student_name of this Student.  # noqa: E501
        :type student_name: int
        :param first_name: The first_name of this Student.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this Student.  # noqa: E501
        :type last_name: str
        :param grades: The grades of this Student.  # noqa: E501
        :type grades: Dict[str, float]
        """
        self.swagger_types = {
            'student_name': int,
            'first_name': str,
            'last_name': str,
            'grades': Dict[str, float]
        }

        self.attribute_map = {
            'student_name': 'student_name',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'grades': 'grades'
        }

        self._student_name = student_name
        self._first_name = first_name
        self._last_name = last_name
        self._grades = grades

    @classmethod
    def from_dict(cls, dikt) -> 'Student':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Student of this Student.  # noqa: E501
        :rtype: Student
        """
        return util.deserialize_model(dikt, cls)

    @property
    def student_name(self) -> int:
        """Gets the student_name of this Student.


        :return: The student_name of this Student.
        :rtype: int
        """
        return self._student_name

    @student_name.setter
    def student_name(self, student_name: int):
        """Sets the student_name of this Student.


        :param student_name: The student_name of this Student.
        :type student_name: int
        """

        self._student_name = student_name

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Student.


        :return: The first_name of this Student.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Student.


        :param first_name: The first_name of this Student.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Student.


        :return: The last_name of this Student.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Student.


        :param last_name: The last_name of this Student.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def grades(self) -> Dict[str, float]:
        """Gets the grades of this Student.


        :return: The grades of this Student.
        :rtype: Dict[str, float]
        """
        return self._grades

    @grades.setter
    def grades(self, grades: Dict[str, float]):
        """Sets the grades of this Student.


        :param grades: The grades of this Student.
        :type grades: Dict[str, float]
        """

        self._grades = grades
